### ISSUE TITLE
Still accurate ?

### ISSUE THREAD

**Issue by julienanquetil** [Smile-SA/magento2-module-elasticsuite-custom-entity#2]
Hi,
This module looks very promissing but as i can see
it's requiere the suite 2.3.4 and not updated since 11 month.

It is on your roadmap again ? Do you have any plan to update it ?

Thanks

**Comment by romainruaud** [comment]
Nope, replaced and refactored in : 

https://github.com/Smile-SA/magento2-module-custom-entity

https://github.com/Smile-SA/magento2-module-custom-entity-product-link
